---
- name: ensure apt cache is up to date
  apt: update_cache=yes cache_valid_time=3600
- name: ensure packages are installed
  apt: name={{item}} state=present
  with_items:
  - postgresql-9.5
  - postgresql-client-9.5
  - libpq-dev
  - python-psycopg2
