---
- name: ensure database volume is formatted
  filesystem:
    fstype: ext4
    dev: /dev/sdb
- name: automount volume
  mount:
    boot: yes
    state: mounted
    fstype: ext4
    src: /dev/sdb
    name: /var/lib/postgresql